name: Run Gradle test

on:
  push:
    branches:
      - main
      - releases/*
  pull_request:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - uses: eskatos/gradle-command-action@v1
      name: Run gradle check
      with:
        arguments: check
